#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

// Display pins
#define DISPLAY1_CS_PIN 10
#define DISPLAY1_DC_PIN 9
#define DISPLAY1_RST_PIN 8

#define DISPLAY2_CS_PIN 7
#define DISPLAY2_DC_PIN 6
#define DISPLAY2_RST_PIN 5

// Button pins
#define BUTTON1_PIN 22
#define BUTTON2_PIN 23
#define BUTTON3_PIN 24
#define BUTTON4_PIN 25
#define BUTTON5_PIN 26
#define BUTTON6_PIN 27
#define BUTTON7_PIN 28
#define BUTTON8_PIN 29
#define BUTTON9_PIN 30
#define BUTTON10_PIN 31
#define BUTTON11_PIN 32
#define BUTTON12_PIN 33
#define BUTTON13_PIN 34
#define BUTTON14_PIN 35
#define BUTTON15_PIN 36
#define BUTTON16_PIN 37
#define BUTTON17_PIN 38
#define BUTTON18_PIN 39

// Button types (voor configuratie)
#define BUTTON_TYPE_PRESET 0
#define BUTTON_TYPE_SCENE 1
#define BUTTON_TYPE_EFFECT 2
#define BUTTON_TYPE_TUNER 3
#define BUTTON_TYPE_LOOPER 4

// Display types
#define DISPLAY_TYPE_ST7735 0
#define DISPLAY_TYPE_ST7789 1

#endif // PIN_DEFINITIONS_H
